"""
scanner/daily.py — the daily-scan entry point.

This is the cron target. Run as:

    python -m src.scanner.daily             # default: dry-run
    python -m src.scanner.daily --apply    # (v0: same as default — apply is a no-op
                                            # until curator.py lands)

Pipeline (v0):
  1. Pull candidates from sources.search_repos (multiple queries).
  2. Apply Filter (language, license, stars, recency).
  3. Deduplicate by full_name.
  4. Write to $SCAN_DIR/candidates.json + drop_reasons.json.
  5. Print a one-screen summary.

Output directory (default):
  $HERMES_HOME/vault/10-minimax/40-scratch/scans/<YYYY-MM-DD>/

The output is the artifact. The next session's agent reads
`<latest>/summary.md` first, before doing anything else.

Safety (v0):
  - Read-only vs. github (GET only; no POST/PUT/DELETE)
  - No LLM calls (curator is a future PR)
  - No patch generation (ingest is a future PR)
  - No PRs (apply is a no-op)
  - Writes only to vault/10-scratch/scans/<date>/
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

from . import sources
from . import filter as filter_mod


# Default query seeds. These are intentionally narrow — the curator
# (when it lands) is the right place to widen. Each query is run
# independently and the union is deduplicated.
DEFAULT_QUERIES: List[Tuple[str, List[str]]] = [
    # (query_text, languages)
    ("gradient flow kernel",       ["python", "rust"]),
    ("projected gradient descent",  ["python"]),
    ("kernel convex optimization", ["python"]),
    ("kernel methods python",      ["python"]),
    ("rust no-std kernel",         ["rust"]),
    ("sheaf neural network",       ["python"]),
    ("geometry of learning",       ["python"]),
    ("rust ndarray tensor",        ["rust"]),
]


def _resolve_scan_dir(today: str) -> Path:
    """Where today's scan artifacts go. Override with $SCAN_DIR."""
    base = os.environ.get("SCAN_DIR")
    if base:
        return Path(base) / today
    # Default: $HERMES_HOME/vault/10-minimax/40-scratch/scans/<date>/
    home = os.environ.get("HERMES_HOME",
                          str(Path.home() / "AppData" / "Local" / "hermes"))
    return Path(home) / "vault" / "10-minimax" / "40-scratch" / "scans" / today


def _write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)


def _write_summary(path: Path, kept: List[sources.Repo],
                   dropped: List[Tuple[sources.Repo, str]],
                   queries_run: int, pages_per_query: int) -> None:
    """Write a one-page summary.md the next session's agent can read first."""
    lines = []
    lines.append(f"# Scanner summary — {path.parent.name}")
    lines.append("")
    lines.append(f"- queries run: {queries_run}")
    lines.append(f"- pages per query: {pages_per_query}")
    lines.append(f"- kept: {len(kept)}")
    lines.append(f"- dropped: {len(dropped)}")
    lines.append("")
    lines.append("## Top kept candidates (by stars)")
    lines.append("")
    lines.append("| repo | stars | language | license | pushed |")
    lines.append("|---|---|---|---|---|")
    for r in sorted(kept, key=lambda r: -r.stars)[:30]:
        lines.append(f"| [{r.full_name}]({r.html_url}) | {r.stars} | "
                     f"{r.language} | {r.license or '-'} | {r.pushed_at[:10]} |")
    if len(kept) > 30:
        lines.append("")
        lines.append(f"... and {len(kept) - 30} more (see candidates.json)")

    # Drop breakdown (top reasons)
    if dropped:
        from collections import Counter
        reasons = Counter()
        for _, why in dropped:
            # Categorize: language=, license=, stars=, pushed_at=, ...
            key = why.split("=", 1)[0].split(" ", 1)[0]
            reasons[key] += 1
        lines.append("")
        lines.append("## Drop breakdown (top reasons)")
        lines.append("")
        for k, v in reasons.most_common(10):
            lines.append(f"- {k}: {v}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("This summary is generated by `python -m src.scanner.daily`.")
    lines.append("v0: read-only, no LLM, no patches. v1: curator + ingest.")
    path.write_text("\n".join(lines), encoding="utf-8")


def run(
    *,
    queries: List[Tuple[str, List[str]]] = None,
    min_stars: int = 200,
    max_age_days: int = 90,
    max_pages: int = 2,
    languages: List[str] = None,
    scan_dir: Path = None,
    apply: bool = False,   # noqa: F841 — kept for CLI symmetry; v0 no-op
    verbose: bool = True,
) -> dict:
    """Run one daily scan. Return a summary dict.

    Args:
        queries: list of (query_text, languages). Defaults to DEFAULT_QUERIES.
        min_stars / max_age_days / max_pages: filter + scrape params.
        languages: if given, override the per-query languages.
        scan_dir: override the output directory.
        apply: v0 no-op. Future versions will run curator + ingest.
        verbose: print progress to stderr.

    Returns:
        {
          "ok": True,
          "date": "2026-09-27",
          "scan_dir": "<path>",
          "queries_run": N,
          "candidates_seen": M,
          "kept": K,
          "dropped": D,
          "kept_files": ["candidates.json", "summary.md", ...],
        }
    """
    queries = queries or DEFAULT_QUERIES
    languages = languages or None
    today = datetime.now().strftime("%Y-%m-%d")
    scan_dir = scan_dir or _resolve_scan_dir(today)

    f = filter_mod.Filter(
        languages=set(languages) if languages else {"python", "rust"},
        min_stars=min_stars,
        max_age_days=max_age_days,
    )

    if verbose:
        sys.stderr.write(f"[scanner] date={today}  scan_dir={scan_dir}\n")
        sys.stderr.write(f"[scanner] filter: lang={f.languages} "
                         f"min_stars={f.min_stars} max_age_days={f.max_age_days}\n")

    all_kept: List[sources.Repo] = []
    all_dropped: List[Tuple[sources.Repo, str]] = []
    seen: set = set()

    for q_text, q_langs in queries:
        if verbose:
            sys.stderr.write(f"[scanner] query: {q_text!r}  languages={q_langs}\n")
        try:
            langs = q_langs if not languages else languages
            repos = list(sources.search_repos(
                q_text,
                languages=langs,
                min_stars=min_stars,
                max_pages=max_pages,
            ))
        except sources.GitHubError as e:
            if verbose:
                sys.stderr.write(f"[scanner] query failed: {e}\n")
            continue

        kept, dropped = filter_mod.apply_filter(repos, f)
        for r in kept:
            if r.full_name in seen:
                continue
            seen.add(r.full_name)
            all_kept.append(r)
        all_dropped.extend(dropped)

    # Write artifacts.
    kept_files = []
    candidates_path = scan_dir / "candidates.json"
    _write_json(candidates_path, [asdict(r) for r in all_kept])
    kept_files.append(str(candidates_path.relative_to(scan_dir)))

    if all_dropped:
        dropped_path = scan_dir / "drop_reasons.json"
        # Only write the (full_name, reason) pairs — not full Repo dicts
        # — to keep the drop file compact.
        _write_json(dropped_path,
                    [{"full_name": r.full_name, "reason": w}
                     for r, w in all_dropped])
        kept_files.append(str(dropped_path.relative_to(scan_dir)))

    summary_path = scan_dir / "summary.md"
    _write_summary(summary_path, all_kept, all_dropped,
                   queries_run=len(queries),
                   pages_per_query=max_pages)
    kept_files.append(str(summary_path.relative_to(scan_dir)))

    if verbose:
        sys.stderr.write(f"[scanner] kept: {len(all_kept)}   dropped: {len(all_dropped)}\n")
        sys.stderr.write(f"[scanner] wrote: {scan_dir}\n")

    return {
        "ok": True,
        "date": today,
        "scan_dir": str(scan_dir),
        "queries_run": len(queries),
        "kept": len(all_kept),
        "dropped": len(all_dropped),
        "kept_files": kept_files,
        "apply": False,   # v0: always False
    }


# --- CLI -------------------------------------------------------------------

def _cli():
    p = argparse.ArgumentParser(
        description="Run the daily repo scan (v0: read-only, no curator, no ingest)."
    )
    p.add_argument("--min-stars", type=int, default=200,
                   help="Minimum stars (default: 200)")
    p.add_argument("--max-age-days", type=int, default=90,
                   help="Max age of last commit in days (default: 90)")
    p.add_argument("--max-pages", type=int, default=2,
                   help="Pages of results per query (default: 2 = 60 results max)")
    p.add_argument("--language", action="append", default=None,
                   help="Language to filter on (repeat for multiple). "
                        "Overrides per-query languages.")
    p.add_argument("--scan-dir", default=None,
                   help="Override the output directory.")
    p.add_argument("--apply", action="store_true",
                   help="v0: no-op. Reserved for v1 curator + ingest.")
    p.add_argument("--queries", default=None,
                   help="Path to a JSON file with custom queries: "
                        "[{\"q\": \"...\", \"languages\": [\"python\", ...]}, ...]")
    args = p.parse_args()

    queries = None
    if args.queries:
        with open(args.queries) as f:
            raw = json.load(f)
        queries = [(q["q"], q.get("languages", ["python", "rust"])) for q in raw]

    result = run(
        queries=queries,
        min_stars=args.min_stars,
        max_age_days=args.max_age_days,
        max_pages=args.max_pages,
        languages=args.language,
        scan_dir=Path(args.scan_dir) if args.scan_dir else None,
        apply=args.apply,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    _cli()